apiVersion: v1 
kind: Service
metadata:
  name: Loadbalancer-svc
spec:
  type: LoadBalancer
  selector:
    app: ngnix
  ports:
    - name: httpd
      protocol: TCP
      port: 80
---
apiVersion: apps/v1
kind: SatefulSet
metadata:
  name: web-sof
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ngnix 
    template:
      metadata:
      labels:
        app: ngnix
    spec:
      containers:
      - name: nginx
        image: gunaeee1994/newimage:latest
        imagePullPolicy: Always
